### ISSUE TITLE
Stratify > Hierarchy

### ISSUE THREAD

**Issue by DDDgfx** [d3/d3-hierarchy#102]
Just a comment here. Spent a long time today trying to make a layout from flat data by using d3.stratify but running into trouble when I then ran the output through d3.hierarchy. Its not clear in the docs that d3.stratify's output is a legit hierarchy object that you can run .count() and .sum() on. Since sum and  count were not listed under stratify, I assumed I had to go through hierarchy to get them. The result was double nested data objects.
It seem like in fact, stratify is the same as hierarchy,  with a preceeding d3.nest stage. Is that true?

**Comment by mbostock** [comment]
d3.stratify and d3.hierarchy do the same thing: they return a root *node*. The difference is that d3.hierarchy constructs a hierarchy (a root node) from a hierarchical input data structure (typically derived from JSON), whereas d3.stratify constructs a hierarchy from a tabular input data structure (typically derived from CSV or TSV).

Both d3.stratify and d3.hierarchy are documented in the Hierarchy section of the README, which includes an example of converting a table to a hierarchy:

```js
var root = d3.stratify()
    .id(function(d) { return d.name; })
    .parentId(function(d) { return d.parent; })
    (table);
```

And it explicitly says “This hierarchy can now be passed to a hierarchical layout, such as d3.tree, for visualization.” The constructor also says it “generates a new hierarchy.”

Apologies for the confusion, but I’m not sure how I can make it clearer…

**Comment by mbostock** [comment]
Thanks for the feedback; related #61 on that *node*.id issue.

**Comment by DDDgfx** [comment]
#62 Understanding this would also have helped.
