### ISSUE TITLE
node.identity() function?

### ISSUE THREAD

**Issue by fbreitwieser** [d3/d3-hierarchy#108]
In addition to to `node.sum()` and `node.count()`, a `node.identity()` function would be very useful when the values of all nodes are already known, and they do not need to be aggregated or recomputed.

Currently I use the following workaround:
```
root.each(function(node) { node.value = node.data[opts.valueField]; });
root.value = d3.sum(root.children, d => d.value); // set root node value
```

**Comment by mbostock** [comment]
Your code snippet suggests you want the *node*.value to be set directly from the data (without a hierarchical sum). I feel *node*.each is already fine for this purpose, as you’re currently doing. In other words, this:

```js
root.identity(data => data.field);
```

Is about as simple as this:

```js
root.each(node => node.value = node.data.field);
```

But I don’t understand the d3.sum in your snippet; if you have precomputed values for all nodes, why are you special-casing the sum for the *root*.value? Is this the behavior you want for *node*.identity, and if so why? Methods on nodes should ideally behave consistently for all parents.

I’m going to close this, but feel free to respond if I’ve misunderstood what you’re asking. Thanks!
