### ISSUE TITLE
Non-centered parent node

### ISSUE THREAD

**Issue by devmsh** [d3/d3-hierarchy#116]
Hi!

Is it possible to draw a hierarchy tree where parent not centered based on the children nodes, we need to have the children in the right side or lift side of the parent?

We review the online examples, source code, without any success!

**Comment by mikol-styra** [comment]
I think we have the same requirement as @devmsh (if I understand him correctly). We want to lay the tree out with the root node at the top left and all descendants cascading down (never up) and to the right. Looking at the d3-hierarchy source, it seems like we’d need to implement a custom layout. Perhaps there are already 3rd-party layouts that do this?

**Comment by mikol-styra** [comment]
Found this: https://bl.ocks.org/mbostock/1093025

**Comment by Tommos0** [comment]
Do you mean something like this maybe: https://github.com/VisualStorytelling/d3-hierarchy/blob/7312254d45355fad2720cad2a6f31d1f3ae05660/img/gratzl.png ? I just opened a pull request for this kind of layout
