### ISSUE TITLE
d3.stratify: would like to have additional method (besides .id and .parentId) to capture data in extra columns

### ISSUE THREAD

**Issue by dan-reznik** [d3/d3-hierarchy#121]
in the examples for d3.stratify(), the input csv/json is a 2-column table (name & parent). however typically additional info about each name could be available in additional columns e.g., age, color, etc.. 

Beyond .id and .parentId accessor functions, I would <3 to also bring into the created hiearchy other columns, e.g., with the "payload" accessor below (imagine "table" contains the columns "name","parent","age","color"):

```{js}
var root = d3.stratify()
    .id(function(d) { return d.name; })
    .parentId(function(d) { return d.parent; })
    .payload(function(d) { return {"age": d.age, "color": d.color }; })
    (table);
```
so now this additional info would also be available in the hierarchy (it comes in handy when you are traversing it). is this possible?

**Comment by mbostock** [comment]
The “payload” is already available in the returned *node*.data. See this example from the README:

https://beta.observablehq.com/d/e622e89f8a5a8f9d
