### ISSUE TITLE
Add documentation distinguishing node.each from node.eachBefore.

### ISSUE THREAD

**Issue by alexlenail** [d3/d3-hierarchy#129]
`.each`

> Invokes the specified function for node and each descendant in breadth-first order, such that a given node is only visited if all nodes of lesser depth have already been visited

`.eachBefore`

> Invokes the specified function for node and each descendant in pre-order traversal, such that a given node is only visited after all of its ancestors have already been visited

`.each` is a "stricter" ordering, -- `.each` meets the criterion of `.eachBefore`. Why include `.eachBefore` in that case?  A single sentence in the README would be helpful here, I think.

**Comment by Fil** [comment]
should the sentence be instead: "each node is visited immediately after its parent and preceding siblings branches have been visited" — quite a mouthful but more accurate?

**Comment by mbostock** [comment]
This is more than covered with our new notebook:

https://observablehq.com/@d3/visiting-a-d3-hierarchy
