### ISSUE TITLE
why the result of use d3.pack is not equal with the wikipedia

### ISSUE THREAD

**Issue by FEliuyg** [d3/d3-hierarchy#132]
when the size of data is 5 or 12, the pack result is not expected。
when i use d3.pack(), the demo result is like [this](https://codepen.io/_xiaoyao/pen/jXNeWG),
this is trend to one side, i hope they are on both size.
the [wikipedia](https://en.wikipedia.org/wiki/Circle_packing_in_a_square)  result is that i want.

**Comment by mbostock** [comment]
You’ll need a different algorithm if you want different results.
