### ISSUE TITLE
d3.treemap should treat negative values as zero.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#134]
Except there’s not an obvious way to do this because *hierarchy*.sum gets called before it’s passed to d3.treemap. If layouts didn’t mutate data #62, then it’d be easier to move the summation into the treemap algorithm and ignore negative values.

**Comment by Fil** [comment]
Is this not simply a documentation / example issue?

```{js}
treemap = data => d3.treemap()
    .tile(tile)
    .size([width, height])
    .padding(1)
    .round(true)
  (d3.hierarchy(data)
      .sum(d => d.value) //  🥺  replace with Math.max(0, d.value) ?
      .sort((a, b) => b.value - a.value))
```

**Comment by mbostock** [comment]
It’s just that people will forget to do that, or not realize they have negative values, and when that happens the treemap algorithm behaves badly.

**Comment by mbostock** [comment]
I think the way to do this is _node_.sumPositive as a variant of _node_.sum that treats negative values are zero.

**Comment by mbostock** [comment]
I’ve updated the treemap chart (and related charts) to wrap the specified _value_ accessor to treat negative values as zero. I think short of folding the value (and sort) operations directly into the treemap layouts, this is basically done.
