### ISSUE TITLE
Accept iterables as children.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#140]
It’d be nice to make d3.hierarchy compatible with the new d3.group in d3-array.

**Comment by Fil** [comment]
Ha I'm exactly at this point
https://observablehq.com/d/d7ae2b6c52756a79#groupCounts3

**Comment by mbostock** [comment]
Related #135, I often find I want to create the simple JSON data structure instead of a d3.hierarchy instance.

**Comment by Fil** [comment]
Here's my current solution
```
hierarchical = d3.group(data, d => d.x, d => d.y, d => d.z);

d3.hierarchy(
  { name: "root", map: hierarchical },
  d =>
    d.map &&
    Array.from(d.map.entries()).map(e =>
      e[1] instanceof Map
        ? { name: e[0], map: e[1] }
        : Object.assign({ name: e[0], values: e[1] })
    )
)
```

**Comment by mbostock** [comment]
Here is my proposal to fix this and #135, d3.children:

```js
function children(values, ...keys) {
  return {
    children: (function node(value, depth) {
      return depth >= keys.length ? value
          : Array.from(value, ([key, value]) => ({key, children: node(value, depth + 1)}));
    })(group(values, ...keys), 0)
  };
}
```

https://observablehq.com/d/59ab45a241d52b98

**Comment by mbostock** [comment]
This also makes me wonder whether we still need a replacement for d3.nest that supports sorting of keys and values…

**Comment by Fil** [comment]
I've tried your code and had to rename `key` to `name` to use @d3/treemap directly. I probably missed something. https://observablehq.com/compare/59ab45a241d52b98...8d4ce02fcb6c6715

**Comment by mbostock** [comment]
That’s expected, but the input format used by that treemap example isn’t really a standard, and the name “key” felt more appropriate. (Perhaps it should be key/values instead of name/children, but then the name d3.nest would be more appropriate than d3.children.)

**Comment by Fil** [comment]
I rewrote https://observablehq.com/d/8d4ce02fcb6c6715 so that the name of each node is computed after the groupby/children operation. Using d3.hierarchy to traverse the json and update the properties.

**Comment by Fil** [comment]
In this case I also needed a reduce operation, so rollup instead of group:
```
function childrenRollup(values, reduce, ...keys) {
  return {
    children: (function node(value, depth) {
      return depth >= keys.length
        ? value
        : Array.from(value, ([key, value]) => ({
            key,
            children: node(value, depth + 1)
          }));
    })(d3.rollup(values, reduce, ...keys), 0)
  };
}
```

**Comment by mbostock** [comment]
Yeah. That’s tricky. We have the existing d3.group and d3.rollup primitives, so this works well:

```js
rollup = d3.rollup(
  raw.filter(d => d.year === "2014").filter(d => d.age === "26+"),
  v => d3.sum(v, d => d.use),
  d => d.drug,
  d => d.state
)
```

Maybe we just need a way to turn that into {name, children} objects? Kind of like *array*.map but applying recursively to map entries… I mean, this works:

```js
({
  children: Array.from(rollup, ([name, children]) => {
    return {
      name,
      children: Array.from(children, ([name, value]) => {
        return {name, value};
      })
    };
  })
})
```

**Comment by mbostock** [comment]
Here’s a way to pass the result of d3.rollup to d3.hierarchy:

```js
d3.hierarchy([, rollup], ([key, value]) => value instanceof Map && Array.from(value.entries()))
```

The data for each node is [*key*, *value*], where the root *key* is undefined, the non-leaf *value* is a Map, and the leaf *value* is a number (the result of the previous d3.sum).

**Comment by mbostock** [comment]
So, in other words, if d3.hierarchy allowed children to be an iterable and not just an array, and automatically ignored children that are not iterable, you would say:

```js
root = d3.hierarchy([, rollup], ([, value]) => value)
```
