### ISSUE TITLE
Customize hierarchy ? Children accessor ?

### ISSUE THREAD

**Issue by StarNab** [d3/d3-hierarchy#147]
I am working with D3 (https://d3js.org/) and php. I ultimately need to create a valid hierarchy for my D3 renderer.

The issue comes from D3 that requires that children are stored in a "children" array belonging to the parent. But my PHP datas are organised like this:

    $myObj['name'] = 'foo';
    ...
    $myObj['unique_id'] = some_hash;
    $myObj['parent'] = the_hash_from_parent_element;

So I need to ultimately achieve something like this

    $myObj['name'] = 'foo';
    ...
    $myObj['unique_id'] = some_hash;
    $myObj['children'] = [$myObj1, $myObj2, ...];

Each $myObj can contain 0 to n objects itself
Therefore I can jsonify the result and send it to my twig template and D3 renderer.

I'm also trying to customize the children accesssor but I'm unable to make it work :(

**Comment by mbostock** [comment]
Looks like you need d3.stratify.

https://observablehq.com/@d3/d3-stratify
