### ISSUE TITLE
Treemap layout (treemapBinary strategy) outputs NaN co-ordinates

### ISSUE THREAD

**Issue by peterrcook** [d3/d3-hierarchy#157]
I'm seeing `x0` and `x1` NaN values when data contains zeroes e.g.

```
var data = [
  {id: 'A', val1: 0, val2: 125},
  {id: 'B', val1: 0, val2: 150},
  {id: 'C', val1: 1, val2: 100}
];
```

If I sum by `val2` or use the default tiling strategy, I don't see NaNs.

Example here:

[https://bl.ocks.org/peterrcook/21c0582665261a5f9d270b01d1a12d76](https://bl.ocks.org/peterrcook/21c0582665261a5f9d270b01d1a12d76)

Maybe related to https://github.com/d3/d3-hierarchy/issues/35

**Comment by mbostock** [comment]
As a notebook for easier inspection and editing:

https://observablehq.com/d/d69b436a2fcc4ed6

It’s almost certainly a divide by zero here:

https://github.com/d3/d3-hierarchy/blob/46f9e8bf1a5a55e94c40158c23025f405adf0be5/src/treemap/binary.js#L37
https://github.com/d3/d3-hierarchy/blob/46f9e8bf1a5a55e94c40158c23025f405adf0be5/src/treemap/binary.js#L41

**Comment by mbostock** [comment]
There’s a similar bug in d3.treemapResquarify, most likely a divide by zero here:

https://github.com/d3/d3-hierarchy/blob/d6adccb2d57db9da4011ee1bead2d8010156ec52/src/treemap/resquarify.js#L21-L22

**Comment by Fil** [comment]
fixed by https://github.com/d3/d3-hierarchy/pull/169/commits/39f420c48982a63161876cbb5412f78d5cd53275
