### ISSUE TITLE
It seems to be a kind of layout error

### ISSUE THREAD

**Issue by seegester** [d3/d3-hierarchy#162]
Hi!

I guess there is off-by-one error or something like that if the elements in hierarchy have similar values. Here is an example of the problem: https://observablehq.com/@seegester/cascaded-treemap.
I used just the same data topology that was in many chart examples, but i modified leaves weights to make all nodes on the same level from top equal. As you can see some blocks (like flare/vis/operator) are missed. But if we tuned weights so all blocks reallocated (just change BUG_THRESHOLD to 3.667) then all that blocks appear.

**Comment by mbostock** [comment]
Looks to be an ordering/occlusion problem in your fork. Here’s the same with a stroke instead of a fill.

![chart (28)](https://user-images.githubusercontent.com/230541/79399904-70c45580-7f39-11ea-8c7f-f938490b0a62.png)
