### ISSUE TITLE
linkRadial can cause links to cross

### ISSUE THREAD

**Issue by thomasahle** [d3/d3-hierarchy#163]
I followed the example of radial tidy trees at https://observablehq.com/@d3/radial-tidy-tree
and generated some large random trees. However, as can be seen on the image, there is a problem with the links, which cross over some of the other parts of the tree.
It seems this is because the links are not 'monotone'.
That is, as things get more spread out, as you go out the link you can get closer to the center of the tree.

I'm not sure if this can be fixed with beizer paths, but in the example https://observablehq.com/@mbostock/tree-of-life it seems to be have been done.

<img width="789" alt="Screen Shot 2020-04-30 at 23 43 19" src="https://user-images.githubusercontent.com/946355/80762268-7bd3d400-8b3c-11ea-9a3e-e783412f37e6.png">

**Comment by mbostock** [comment]
This is the expected behavior. You’re welcome to implement something else, but I think it would be tricky.

**Comment by thomasahle** [comment]
I see. Your Tree of Life graph uses circle arcs. Do you think it would be nice to have a built-in link function for those? I can write up a draft.

**Comment by mbostock** [comment]
The Tree of Life notebook uses the equivalent of orthogonal (square-cornered) links in polar coordinates. Converting cubic Bézier curves in Cartesian coordinates into polar coordinates would be quite challenging; I’m assuming it’d only be feasible to do an approximation.

**Comment by thomasahle** [comment]
I wasn't thinking about Bézier curves.
Just that something like the following might be nice to have as an alternative link form:

```
function linkRadial2() {
   return link(curveArc);
}

function curveArc(context, r0, a0, r1, a1) {
  var p0 = d3.pointRadial(a0, r0),
      p1 = d3.pointRadial(a0, (r0 + r1) / 2),
      p2 = d3.pointRadial(a1, (r0 + r1) / 2),
      p3 = d3.pointRadial(a1, r1);
  context.moveTo(p0[0], p0[1]);
  context.lineTo(p1[0], p1[1]);
  context.arc(0, 0, (r0+r1)/2, a0-Math.PI/2, a1-Math.PI/2, a1<a0);
  context.moveTo(p2[0], p2[1]);
  context.lineTo(p3[0], p3[1]);
}
```

**Comment by mbostock** [comment]
Oh sure, if that’s all what you want, that’s doable. We can call that linkStepRadial.

**Comment by thomasahle** [comment]
The idea of using beizer paths approximating arcs sounds really exciting, but I agree that it would be quite difficult. The arc links work well enough for me.

**Comment by thomasahle** [comment]
One issue with this linkStepRadial is that the lines coming out of a parent node all overlap, making the line look thicker before it branches out.

Another issue is the `moveTo` call after `arc`, which makes the svg linejoins not look as great.

Are there some obvious ways to get rid of those problems that I'm overlooking?
