### ISSUE TITLE
Treemap leaf nodes with rect height = 0

### ISSUE THREAD

**Issue by mdbaehre** [d3/d3-hierarchy#164]
When I create a treemap with parent nodes that contain only 1 or 2 leafnodes it can result in leafnodes that have y0 = y1 after running the treemap function resulting in leafnode "rect"s that have a height = "0" and do not display.  This happens more frequently when I include a paddingTop value to large enough to label the parent nodes.

**Comment by mbostock** [comment]
This sounds like the expected behavior if the leaf nodes have zero (or near-zero with padding and rounding) value. If you’d like me to investigate, please share an example that demonstrates the problem, preferably as an Observable notebook. Thanks.
