### ISSUE TITLE
How can I handle the ts error "Type 'number | undefined' is not assignable to type 'number'." ?

### ISSUE THREAD

**Issue by takeItIzzy** [d3/d3-hierarchy#168]
```js
const regions =
  data &&
  d3
    .hierarchy('data')
    .sum((d) => 1)
    .sort((a, b) => b.value - a.value);
```
The callback of sort() will throw an error `Object is possibly 'undefined'.` when I use typeScript, and if I add a condition like this:
```js
const regions =
  data &&
  d3
    .hierarchy('data')
    .sum((d) => 1)
    .sort((a, b) => {
      if (a.value && b.value) {
        return b.value - a.value;
      }
    });
```
It'll say `Type 'number | undefined' is not assignable to type 'number'.` How can I handle with it?

**Comment by Fil** [comment]
Please address D3 typescript queries to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3

PS: I am surprised by the quotes around 'data' in the hierarchy() call.
