### ISSUE TITLE
Seemingly non-weird ball collection throws an error in d3.packEnclose()

### ISSUE THREAD

**Issue by esperanc** [d3/d3-hierarchy#188]
The following set of balls throws an error:

```
let weirdBalls = [
  { x: 14.5, y: 48.5, r: 7.585 },
  { x: 9.5, y: 79.5, r: 2.585 },
  { x: 15.5, y: 73.5, r: 8.585 }
] 
d3.packEnclose(weirdBalls)
```

Note that these do not seem weird in the sense of having centers that are too close or too small/too big radii. 
I tracked down the error to function `encloseBasis3`, which has the following conditional assignment: 

```
const r = -(A ? (B + Math.sqrt(B * B - 4 * A * C)) / (2 * A) : C / B);
```

For this particular data set, `A == 4.440892098500626e-16`, and my proposed solution is to test for a 'small enough' A :

```
const r = -(Math.abs(A) > 1e-10
      ? (B + Math.sqrt(B * B - 4 * A * C)) / (2 * A)
      : C / B);
```

This seems to work in a project which creates quite a few circles, but there is probably a better solution.

**Comment by mbostock** [comment]
Yes, that looks right to me. encloseBasis3 is generating a circle that doesn’t enclose the three circles (red); the fix you propose looks correct (blue).

![untitled (3)](https://user-images.githubusercontent.com/230541/161402960-b2250445-d13e-40c4-8bfd-884629b2341c.png)

And just for completeness, none of the 2-basis will be correct here.

![untitled (4)](https://user-images.githubusercontent.com/230541/161402986-89857807-5270-480a-82dd-5e6c2d3e6950.png)
