### ISSUE TITLE
Automatically box non-hierarchy instances?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#42]
What if this:

```js
var root = treemap(data);
```

Were equivalent to this:

```js
var root = treemap(d3.hierarchy(data).sum(function(d) { return d.value; }));
```

You might even sort by default, like this?

```js
var root = treemap(d3.hierarchy(data)
    .sum(function(d) { return d.value; })
    .sort(function(a, b) { return b.value - a.value; }));
```

And perhaps this:

```js
var root = treemap(data, function(d) { return d.size; });
```

Could be equivalent to this (sorting TBD):

```js
var root = treemap(d3.hierarchy(data).sum(function(d) { return d.size; }));
```

Which is a bit like how the d3-array methods take value accessors. It would add a bit of code to each hierarchy layout, but it feels like it might be convenient for the common case… albeit less self-describing.

**Comment by syntagmatic** [comment]
This seems too magical to be worth it, at least from the perspective of transitioning from version 3. There will be considerable confusion about hierarchy formats because of issues like https://github.com/d3/d3-collection/issues/3

The d3.hierarchy API is useful to encounter and read about, so explicitly declaring it is good for now.

The automatic boxing probably can't work both with code that uses the existing d3.nest (key/values) and the flare.json (name/children) structures... or can it?

**Comment by mbostock** [comment]
I don’t think you’d want automatic boxing to allow the children to be defined using the values property by default. That would imply d3.hierarchy would allow either, as well, and that seems unnecessary. If we changed d3.nest according to d3/d3-collection#3, old code like this:

```js
var root = treemap(d3.hierarchy({values: nest.entries(data)}, function(d) { return d.values; }).sum(function(d) { return d.values; }));
```

Could be changed to this:

```js
var root = treemap({children: nest.entries(data)});
```

In other words:

* You don’t need to specify a *children* accessor to d3.hierarchy because the default one is now compatible with d3.nest.
* You don’t need to pass the result of *nest*.entries to d3.hierarchy because the hierarchy layout (*treemap*) automatically does that if the input isn’t a d3.hierarchy instance.
* You don’t need to call *hierarchy*.sum, either, because the hierarchy layout automatically does that if the input isn’t a d3.hierarchy instance.
* You don’t have the confusion of *entry*.values referring to either the children values or the rolled-up value because *nest*.rollup replaces the leaf entries with {key, value} objects.

Now, you could just take d3/d3-collection#3 by itself and not allow autoboxing, in which case you’d need to say this:

```js
var root = treemap(d3.hierarchy({children: nest.entries(data)}).sum(function(d) { return d.value; }));
```

Or you could just support autoboxing and reject d3/d3-collection#3, in which case the example here would remain unchanged since d3.nest wouldn’t be able to take advantage of autoboxing. But autoboxing would still help if you had hierarchical JSON data and you just wanted the default behavior in regards to sorting.

**Comment by mbostock** [comment]
Okay, I think I’m against autoboxing in that: it doesn’t introduce the d3.hierarchy API (and violates parsimony); it requires specifying default behavior in all hierarchy layouts; and it’s not useful in the case where you have tabular data and need to use d3.stratify.
