### ISSUE TITLE
Example Code under node.sort(compare)

### ISSUE THREAD

**Issue by tomwanzek** [d3/d3-hierarchy#48]
The first example under the [node.sort(compare)](https://github.com/d3/d3-hierarchy#node_sort) contains the code snippet:
```
.sort(function(a, b) { return b.value - a.value; });
```
This should probably read:
```
.sort(function(a, b) { return b.data.value - a.data.value; });
```
as the sort function passes in nodes.

**Comment by mbostock** [comment]
The code is correct as-is; it is sorting by the aggregate values computed and set by *node*.sum on the previous line, not the *data*.value.

**Comment by tomwanzek** [comment]
Apologies, skipped over the implication of the `sum(...)` call in the prior line too quickly :disappointed: . 

On a related aside then, maybe it would be valuable, pardon the pun, to add the `value` property as an optional node property to passage starting with:

> The returned node and each descendant has the following properties:

e.g.:
* *node*.value - aggregated numeric value, if any,  as calculated by [node.sum(value)](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sum)

Just an idea from someone who seems to have read too fast. Your call.

**Comment by mbostock** [comment]
That’s a nice idea. I’ll make that change unless you beat me to it! Thanks.

**Comment by tomwanzek** [comment]
Clearly you beat me to it... :smile:
