### ISSUE TITLE
Bug in treemapDice in K value calculation

### ISSUE THREAD

**Issue by dvreed77** [d3/d3-hierarchy#56]
Found a bug in treemapDice that calculates an incorrect k value.  Since `parent.value` includes the count of itself, k should be calculated as follows:

```javascript
k = parent.value && (x1 - x0) / (parent.value-1)
```

rather than

```javascript
k = parent.value && (x1 - x0) / parent.value
```

Found this bug since there were tiny gaps at the bottom of my partition map that was equal to size of the leaf node.

**Comment by mbostock** [comment]
The current behavior is correct. You didn’t link to a live example that demonstrates your issue, but I’m guessing that you passed *node*.sum a value accessor that is returning a non-zero value for internal nodes, and so it is reserving space for the internal nodes’ self-values. This was already described in the README for [*node*.sum](https://github.com/d3/d3-hierarchy#node_sum), but I’ve updated the example to make it a little bit clearer.

http://bl.ocks.org/mbostock/b4c0f143db88a9eb01a315a1063c1d77

**Comment by dvreed77** [comment]
@mbostock thank you... this makes much more sense now
