### ISSUE TITLE
Add ability to customize tree layout

### ISSUE THREAD

**Issue by Misiu** [d3/d3-hierarchy#66]
For small trees default layout engine works fine, like in [this](http://bl.ocks.org/d3noob/8326869) example, but for larger trees (especially with many child nodes) default layout takes so much place.

I'd like to be able to specify type of layout for child nodes, to get [this](http://live.yworks.com/demobrowser/#Organization-Charts) behavior.

So instead of 
![n4koi](https://cloud.githubusercontent.com/assets/1741838/20310349/f1ca981c-ab4b-11e6-95d8-3c47eae227a3.png)

I would get this layout
![haoft](https://cloud.githubusercontent.com/assets/1741838/20310365/013281e8-ab4c-11e6-87c7-a7b4edc768ce.png)

I found [this question ](http://stackoverflow.com/questions/18108960/d3-tree-layout-custom-vertical-layout-when-children-exceed-more-than-a-certain)on StackOverflow, but it is from 3 years ago so maybe something new was added that would allow this layout.

[yFiles Organization Chart](http://live.yworks.com/demobrowser/#Organization-Charts) is ideal example of layout I have in mind.

Main idea is to "pack" items together and display as much as possible without need to scroll horizontally.

**Comment by mbostock** [comment]
I’ve no plans to implement this, but you’re of course welcome to fork the existing hierarchy layouts or implement you own. Good luck!

**Comment by Misiu** [comment]
![snap 2017-06-26 at 11 21 48](https://user-images.githubusercontent.com/1741838/27532804-af048efa-5a61-11e7-83e9-556b9a5cc041.png)

This was quite easy to build, however I'm thinking about rewriting this after https://github.com/d3/d3-hierarchy/issues/62, https://github.com/d3/d3-hierarchy/issues/63 and https://github.com/d3/d3-hierarchy/issues/64 are fixed.

Also please consider adding example of how to extend a layout.
