### ISSUE TITLE
Iteration methods such as node.eachBefore should pass the index, too.

### ISSUE THREAD

**Issue by nathanbowser** [d3/d3-hierarchy#67]
I'm upgrading some code from v3 to v4. I think it'd be useful for `eachBefore` and perhaps the other loops to receive an index. e.g. Migrating this block: http://bl.ocks.org/mbostock/1093025

**Comment by mbostock** [comment]
I support this change. It would need to be done consistently across all node iteration methods.

**Comment by mbostock** [comment]
Implemented in 62a6211592ec7eb344864a72100f1254c824879a.
