### ISSUE TITLE
Problems with the treemap Algorithem.

### ISSUE THREAD

**Issue by mark3448** [d3/d3-hierarchy#68]
Trying to follow the examples i met a strange glitch in the treemap code, can't seem to find the problem.
here is a fiddle with the problem:
https://fiddle.jshell.net/40xoLecy/

same code with different data works well:
https://fiddle.jshell.net/40xoLecy/3/

what seems to be the problem with the layout? why is it a a pile of rects?

**Comment by mark3448** [comment]
after playing a bit with the data, i found out the 0 is what makes the pile problem , why aren't 0 allowed?

**Comment by mbostock** [comment]
Unrelated to your issue (which I am investigating), but you don’t need d3.stratify to create a flat tree. You can use d3.hierarchy:

```js
var rootNode = d3.hierarchy({children: clonedData}).sum(d => d);
```

**Comment by mark3448** [comment]
Thank you for the quick fix, any date on the release?
