### ISSUE TITLE
Pack layout should allow parent padding? (“Margin”?)

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#7]
Related mbostock/d3#2536; see [demo](http://bl.ocks.org/larskotthoff/085bb57f710aa417af41).

**Comment by mbostock** [comment]
I’m not sure about the name “margin”; maybe it’s worth having sibling padding and parent padding? Or maybe padding should automatically apply to the parent circle, not just the siblings.

**Comment by larskotthoff** [comment]
I like the idea of having just one padding that applies to both parent and siblings.

**Comment by mbostock** [comment]
Seems reasonable to me, too.

**Comment by mbostock** [comment]
Related question: Should the padding be configurable per node? Seems like you could compute the padding per node if it is specified as a function, and it would apply to padding between that node and its children (parent-child padding), and amongst its children (sibling padding).

**Comment by mbostock** [comment]
Related #9.

**Comment by larskotthoff** [comment]
Yep, it would certainly be good to have it configurable per node as well. Sounds like mbostock/d3#2473 would be a more general solution to this.

**Comment by mbostock** [comment]
Fixed.

**Comment by mbostock** [comment]
[![screen shot 2016-03-22 at 1 07 01 pm](https://cloud.githubusercontent.com/assets/230541/13966317/038b1000-f02f-11e5-9bdb-c62068c07949.png)](http://bl.ocks.org/mbostock/ca5b03a33affa4160321)
