### ISSUE TITLE
tree function fails on empty children list

### ISSUE THREAD

**Issue by Flowdihow** [d3/d3-hierarchy#70]
I am using filter to filter children of a particular datum. However, if the list is empty the tree method fails:

> d3.v4.js:9926 Uncaught TypeError: Cannot read property 'z' of undefined

This is caused by the following lines:
```javascript
if (children) {
      executeShifts(v);
      var midpoint = (children[0].z + children[children.length - 1].z) / 2;
...
```
In the documentation, it is stated that children must be null, if a particular datum has no children. However, I have mixed feelings about checking for being true, but expecting a list with at least one member.

Thanks!
Flo

**Comment by mbostock** [comment]
When filtering children, you must set node.children to null if the array of children is empty. (The code you included does not check whether children is true, but whether children is “truthy”; null is falsely while an empty array is truthy, hence the requirement to set the children to null when there are no children.)

The code could be rewritten to all either condition, or to instead require the empty array when there are no children, but such a change would like require a major version bump and I have no immediate plans to implement it.

**Comment by Richard-biz** [comment]
Hi @mbostock 
 d3 is Really  Awesome , it is help me the more functionality of my Web application, now i am facing the "Z undefined" issue, Could you tell me Still the Issue was is there  when you will be implement else could you give me the Code sample of this. i am not much knowledge about D3 so if you share me your knowledge , It will helpful of me to continue on my work.

**Comment by Richard-biz** [comment]
Hi There I got the Solution for the issue if you follow this Link you can solve the issue of Children null "https://stackoverflow.com/questions/42602419/d3-v4-drag-drop-tree-node-into-new-parents-children/42603707#42603707"
Its due to Children node null and Parent Node Depth issue.

**Comment by Cactusx09** [comment]
In my case i'am getting this error when i try to remove my last children node with:
`selected.children.pop();`
and then update my tree. 
I'am simply set last children to null and it's worked. 
`if(selected.children.length == 0){
    selected.children = null;
    this.update(selected);
  }else{
    this.update(selected);
  }`
Thnx @mbostock for saving my time!

**Comment by nick-running** [comment]
I would like use these code to remove node 
`document.querySelector('#delete').addEventListener('click', function () {
    let selected = selectedTreeNode.node
    let children = [], dataChildren = []
    selected.parent.children.forEach((n,i)=>{
      if(n.id!==selected.id) {
        children.push(n)
        dataChildren.push(n.data)
      }
    })
    selected.parent.children = children.length?children:null
    selected.parent.data.children = dataChildren.length?dataChildren:null
    update(selected.parent)
  })`

**Comment by nick-running** [comment]
I would like to use there code to remove node 

> document.querySelector('#delete').addEventListener('click', function () {
    let selected = selectedTreeNode.node
    let children = [], dataChildren = []
    selected.parent.children.forEach((n,i)=>{
      if(n.id!==selected.id) {
        children.push(n)
        dataChildren.push(n.data)
      }
    })
    selected.parent.children = children.length?children:null
    selected.parent.data.children = dataChildren.length?dataChildren:null
    update(selected.parent)
  })
