### ISSUE TITLE
Split treemaps?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#71]
As described in “Ordered and Unordered Treemap Algorithms and Their Applications on Handheld Devices” by Engdahl.

**Comment by timelyportfolio** [comment]
inspired by @thomasp85 ggforce implementation and the original paper, I have assembled an ugly mix of code from these two sources and other d3 treemap code.  Before I submit pull with proper tests, I wanted to first make sure that this (with much revision of course) would be welcome.

@mbostock I forked your d3 source treemap (thanks so much for this!) and applied the new split algorithm http://bl.ocks.org/timelyportfolio/e480359ea953d96a38a4466187d3d62b.

<img width="613" alt="d3_treemap_split" src="https://cloud.githubusercontent.com/assets/837910/21063954/ed583f34-be1d-11e6-8742-b1cea202879b.png">

In just a little bit, I will also apply the d3v4 treemap with `tile` input to more closely inspect differences.

**Comment by mbostock** [comment]
Fantastic! Implementation looks relatively straightforward which is always nice! Thank you for doing this and I look forward to the PR.

**Comment by timelyportfolio** [comment]
Just converted this to add `treemapSplit` http://bl.ocks.org/timelyportfolio/2bbd4cedf597eae6a5e90412d9df1c1f.  (Had no idea `d3.hierarchy` had changed so much since this early iteration).  I absolutely love all the convenience functions added in `d3.hierarchy`.

**Comment by timelyportfolio** [comment]
started and it seems to work correctly on smaller test networks and the d3 source example with much better speed, but now on my [test on a larger network](http://bl.ocks.org/timelyportfolio/285dcaecf159c01849b3a48b0a35cec3) I get

```
Uncaught RangeError: Maximum call stack size exceeded(…)
```  

I'll research and debug.

**Comment by timelyportfolio** [comment]
Certainly no rush whatsoever, but is this something you would like me to continue to push forward?  Thanks for everything, and please, please, please let me know if ever in any strange little way whatsoever I can help you in any way.

**Comment by mbostock** [comment]
Turns out—with a bug fix and a small improvement—these are the same thing as [binary treemaps](https://github.com/d3/d3-hierarchy/blob/master/README.md#treemapBinary) which were implemented in [d3-hierarchy@1.0](https://github.com/d3/d3-hierarchy/releases/tag/v1.0.0) ([d3@4.0](https://github.com/d3/d3/releases/tag/v4.0.0))!

**Comment by timelyportfolio** [comment]
👍 good learning experience.  Thanks!
