### ISSUE TITLE
Circle packing sometimes overlaps circles.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#74]
From d3/d3#3045, @sheldon-white writes:

> I've reproduced this with a couple of large datasets; there's some unexpected overlaps in some of the circles. I haven't been able to recreate this with a small dataset so far. I've attached a screenshot, a datafile and example page that shows the issue.
> 
> ![](https://cloud.githubusercontent.com/assets/1130768/21513920/08da21ec-cc73-11e6-8c39-169ac069a0e7.png)
> 
> [bugreport.zip](https://github.com/d3/d3/files/675039/bugreport.zip)

**Comment by mbostock** [comment]
There is a bug in d3.pack here, but it is being triggered by a bug in your code. Specifically here, where you say:

```js
root.sort(function(a, b) { return b.lines - a.lines; });
```

Unlike [*node*.sum](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sum), which passes the accessor function the node’s data, [*node*.sort](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sort) passes the comparator function two nodes (not two data!). This is because *node*.sort typically operates on the sum computed by *node*.sum. So your comparator returns NaN when sorting two non-leaf nodes, and that means that the behavior of *array*.sort (and by extension *node*.sort) is undefined and may vary across browsers.

You should instead say:

```js
root.sort(function(a, b) { return b.value - a.value; });
```

And this indeed fixes the problem. Before:

<img width="1264" alt="screen shot 2016-12-28 at 10 14 19 am" src="https://cloud.githubusercontent.com/assets/230541/21528305/746c84c2-cce6-11e6-8915-61305ca7cf40.png">

After:

<img width="1268" alt="screen shot 2016-12-28 at 10 10 49 am" src="https://cloud.githubusercontent.com/assets/230541/21528307/7b6ba456-cce6-11e6-89ee-809fad2cd526.png">

I think the problem here is that the circle-packing layout is initially placing a few very small circles and there is numerical instability because the circles are so small. It’s possible that this is impractical to fix in the library, or that we’ll need a cludgy workaround like treating all circles smaller than ε as zero.

I reduced your test case here: http://bl.ocks.org/mbostock/1eb59d8139b3bea5c71e46afee440f9e

**Comment by mbostock** [comment]
Reduced to the following input:

```json
{"path":"/","children":[
  {"path":"/a","value":3},
  {"path":"/b","value":30},
  {"path":"/d","value":50},
  {"path":"/c","value":400},
  {"path":"/e","value":600}
]}
```

<img width="402" alt="screen shot 2016-12-28 at 10 57 19 am" src="https://cloud.githubusercontent.com/assets/230541/21529159/736d13f6-ccec-11e6-9f13-f3dd5d53ed51.png">

**Comment by mbostock** [comment]
This one also fails, in a different way:

```json
{"path": "/", "children":[
  {"path": "/a", "value": 3},
  {"path": "/b", "value": 70},
  {"path": "/d", "value": 100},
  {"path": "/c", "value": 200},
  {"path": "/e", "value": 500}
]}
```

<img width="555" alt="screen shot 2016-12-28 at 11 00 30 am" src="https://cloud.githubusercontent.com/assets/230541/21529237/e9229328-ccec-11e6-8c2d-a9eed128199b.png">

**Comment by thomasp85** [comment]
I can reproduce these errors in my C++ implementation in ggraph. Naively I would guess that it is related to bad overlap checking when one circle completely encloses the other... I will get back once I've squashed the bug in ggraph

**Comment by mbostock** [comment]
The problem with my implementation is that in these cases it splices the wrong part of the front chain; the overlapping circle is found, but it is not clear whether the offending circle is “in front” or “in back” of the two tangent circles that were used to place the new circle. These terms are not defined in the paper.

Splicing the front chain should always make the front chain polygon bigger, so the fix I will attempt when I ever get a free moment is to compare the area of the front chain that would be added by splicing in either direction, and always splice the direction where this area is positive. Only one direction should be positive, I think… though if that is not the case then I will have to try another strategy.

**Comment by thomasp85** [comment]
FWIW preferring to check backwards first has solved all your proposed minimal cases. While I can understand why this is for the small examples you gave I have a bit of a hard time understanding if it should generalise...

**Comment by mbostock** [comment]
If you check backwards first, but reverse the order of circles in the above test cases, does the overlap reappear? I’d also try futzing with the orders of the circles more to further test your proposed change.

**Comment by thomasp85** [comment]
I tried a few permutations without problems but since the test case is so small I'll just run all sorting orders and see if there's any problems- I'll get back

**Comment by thomasp85** [comment]
My bad - problems still crop up...

![rplot04](https://cloud.githubusercontent.com/assets/1775316/22162417/f03ee2a0-df4e-11e6-86b3-3279a9b3717e.png)

**Comment by mbostock** [comment]
I appear to have fixed this bug! 🎉 

![pack](https://cloud.githubusercontent.com/assets/230541/22398116/c49a6af6-e535-11e6-8157-14661227b576.png)

**Comment by curran** [comment]
@mbostock I'm just curious, how did you create that high resolution image? Is it an SVG exported from the browser then rasterized?

**Comment by mbostock** [comment]
@curran I used SVG Crowbar to save from the browser and then graphicsmagick to convert to PNG, and optipng to optimize it.

**Comment by curran** [comment]
@mbostock Sweet! Thanks for the reply. Interesting tools.
