### ISSUE TITLE
d3.stratifyDot? d3.stratifySlash?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#75]
It’d be nice to have this convenience method for dot-separated ids such as Java class names:

```js
d3.stratifyDot = d3.stratify().parentId(d => d.id.substring(0, d.id.lastIndexOf(".")));
```

Similarly for path names?

```js
d3.stratifySlash = d3.stratify().parentId(d => d.id.substring(0, d.id.lastIndexOf("/")));
```

**Comment by mbostock** [comment]
They should be immutable, of course:

```js
var stratifyDot = d3.stratify().parentId(d => d.id.substring(0, d.id.lastIndexOf("."))),
    stratifySlash = d3.stratify().parentId(d => d.id.substring(0, d.id.lastIndexOf("/")));

d3.stratifyDot = function(data) {
  return stratifyDot(data);
};

d3.stratifySlash = function(data) {
  return stratifySlash(data);
};
```

**Comment by mbostock** [comment]
Or with implied parents (#33):

```js
var stratifyDot = d3.stratify().ancestorId(id => id.substring(0, id.lastIndexOf("."))),
    stratifySlash = d3.stratify().ancestorId(id => id.substring(0, id.lastIndexOf("/")));

d3.stratifyDot = function(data) {
  return stratifyDot(data);
};

d3.stratifySlash = function(data) {
  return stratifySlash(data);
};
```

**Comment by mbostock** [comment]
So, it might be nice if it’s configurable, since you could have *datum*.path rather than *datum*.id (*e.g.*, the [D3 source treemap](https://bl.ocks.org/mbostock/8fe6fa6ed1fa976e5dd76cfa4d816fec)’s [d3.csv](https://gist.githubusercontent.com/mbostock/8fe6fa6ed1fa976e5dd76cfa4d816fec/raw/122aa364ef1b0134455654f446e15dbfd1c95f86/d3.csv)). In that case, you might want to do something like this:

```js
var root = d3.stratifySlash().id(d => d.path)(data);
```

Though perhaps it could be an optional accessor, like d3-array methods:

```js
var root = d3.stratifySlash(data, d => d.path);
```

Either way it’s certainly simpler than:

```js
d3.stratify()
    .id(d => d.path)
    .parentId(d => d.path.substring(0, d.path.lastIndexOf("/")))
  (data)
```

**Comment by seemantk** [comment]
Hi @mbostock.  This is a really cool module.  Wondering if you'd consider having the delimiter be specifiable?  Something like `d3.stratify().delim('/')` perhaps?  Delimiters could be slashes, underscores, colons, etc (so far in my use cases, I've got colons and periods).

**Comment by mbostock** [comment]
Those other approaches are all possible using d3.stratify directly as the general solution. If we generalize “d3.stratifySlash” too much the it won’t be more useful than the existing d3.stratify.

**Comment by mbostock** [comment]
I feel this is mostly addressed by the new _stratify_.path #185. That could be extended to take a different delimiter, but you can also remap the input to use slashes, too (just be careful about escaping).
