### ISSUE TITLE
node.count.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#76]
The proposed method for only counting leaf nodes is a little brittle:

```js
root.sum(function(d) { return d.value ? 1 : 0; });
```

Specifically, it requires that *node*.data.value is truthy for leaf nodes, and falsey for internal nodes. In general this may not be true, so the “correct” way to count leaf nodes requires using *node*.eachAfter. Since this seems generally useful, I propose exposing it as *node*.count:

```js

function count(node) {
  var sum = 0,
      children = node.children,
      i = children && children.length;
  if (!i) sum = 1;
  else while (--i >= 0) sum += children[i].value;
  node.value = sum;
}

export default function() {
  return this.eachAfter(count);
}
```

**Comment by zfrenchee** [comment]
@mbostock could you document this just slightly more in the README, perhaps with a simple code example? 
```
        metadata = d3.hierarchy(obj).count();
```
Does not properly assign `value` to my nodes. Perhaps I'm doing something else wrong, but I'm guessing I'm just not using the method properly. If that's the case, I think a simple code example in the [README](https://github.com/d3/d3-hierarchy#node_count) could help.
