### ISSUE TITLE
node.find?

### ISSUE THREAD

**Issue by jacobp100** [d3/d3-hierarchy#94]
It would be useful to have a `node#find` function.

In addition, in Lodash, returning `false` in a `forEach` callback exits early. This would be useful in `node#each` for performance optimisations for custom iteration functions.

Happy to submit a PR if you want to go in this direction.

**Comment by mbostock** [comment]
I’d support a *node*.find PR.

I wouldn’t support short-circuiting *node*.each if the callback returns false, though; that would not be backwards compatible nor consistent with standard array methods. It’d be better to either use *node*.find for that purpose, or if we like, we could have *node*.some and *node*.every methods equivalent to the standard array methods.

**Comment by mbostock** [comment]
Added in 5e8701ca0dc672597b0f29fa47178a575c699cc2.
