### ISSUE TITLE
node.reduce?

### ISSUE THREAD

**Issue by timelyportfolio** [d3/d3-hierarchy#95]
In many cases, I need to summarize or aggregate levels with calculations other than `sum` and `count`.   While this is fairly easy now with the new d3v4 `eachAfter()` functionality, would there be a use case for some more generalized form of `hierarchy.sum` and `hierarchy.count`?  I envision something like this unoptimized function that acts much like `reduce`.

```
export default  function (f, valuef, name) {
      return this.eachAfter(function(node) {
        var children = node.children,
          values;
        if(children && children.length) {
          values = children.map(function(d){return d[name]});
        } else {
          values = [valuef(node)];
        }
        var agg = f(values);

        node[name] = agg;
      });
    }
```

Here is an [example](https://bl.ocks.org/timelyportfolio/612c434485cfccddfa15049bbeb099c9).

**Comment by mbostock** [comment]
A *node*.reduce method would be welcome, following the same API pattern as *array*.reduce.

**Comment by timelyportfolio** [comment]
Ok, I hope to get to this over the next couple of days.  I'll also say thank you one more time for your generous and exceptional efforts with `d3` and other packages!

**Comment by timelyportfolio** [comment]
Little more than a couple of days, but I am getting to this.  Should the `node.reduce()` assign to `node.value` as is done with `node.sum()` [line](https://github.com/d3/d3-hierarchy/blob/master/src/hierarchy/sum.js#L7)?

In my original example, I had an argument for `name` used for the object key where we assign the result.

Do you have a preference?

**Comment by mbostock** [comment]
Yes, I would have it assign to *node*.value. (*node*.count does this as well.)

**Comment by Fil** [comment]
A question is what to do with initialValue (which would be aggregated from each branch).

Wouldn't it be nice also to have:
-  node.map() 
> (currently doing `node.descendants().map(d => d.data).map(myFunction)`)
- node.nodes()
> alias of node.descendants()
- node.length
> alias of node.descendants().length

**Comment by mbostock** [comment]
Closing to inactivity.
